# Custom Language File for Launcher Customizer

[ejs.app]
title = "Helios Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/createye/SeverLauncher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/B47xfKKv"

[ejs.settings]
sourceGithubLink = "https://github.com/createye/SeverLauncher"
supportLink = "https://github.com/createye/SeverLauncher/issues"

[ejs.welcome]
welcomeHeader = "메트로폴리스에 오신걸 환영합니다"
welcomeDescription = "메트로폴리스는 현실 경제 서버입니다!"
welcomeDescCTA = "즐겁게 게임을 플레이 해주세요!"
